apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-12-09T00:29:51Z"
  labels:
    kubernetes.io/metadata.name: cka-lab-q1
  name: cka-lab-q1
  resourceVersion: "9921"
  uid: e49727eb-e13b-4cb6-975a-7e314466106c
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
