apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: web-pod
  name: web-svc
  namespace: cka-lab-q1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: web-pod
status:
  loadBalancer: {}
