apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api-deploy
  name: api-deploy
  namespace: cka-app-q2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-deploy
    spec:
      containers:
      - image: nginx:1.21
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
