apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: client-pod
  name: client-pod
  namespace: web-ns-q6
spec:
  containers:
  - image: busybox:1.36
    name: client-pod
    command: ["sh","-c","sleep 3600"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
